### ISSUE TITLE
Cannot find v_HandStandPushups_g08_c01.hdf5

### ISSUE THREAD

**Issue by billhhh** [yanbeic/CCL#3]
Hi,

Thank you for sharing such good codes and work.

When I tried to generate the json files, ../data/UCF101/UCF101_hdf5/HandstandPushups/v_HandStandPushups_g08_c01.hdf5 to ../data/UCF101/UCF101_hdf5/HandstandPushups/v_HandStandPushups_g07_c04.hdf5. It returns Cannot find the file...

I tried to regenerate the hdf5 of HandstandPushups, the problem is still there.
Really appreciate if you can offer some help!

Best,
Hu

**Comment by jamzhong1** [comment]
Firstly, download the UCF101 video datasets and run the generate_video_hdf5.py. When you check the "datasets/UCF101/hdf5data" that svaed hdf5 file, you can find that v_HandStandPushups_g07_c04.hdf5 is different from v_HandstandPushups_g07_c04.hdf5, you just rename v_HandStand* as  v_Handstand*.

**Comment by billhhh** [comment]
I think it has been solved, thank you! It is caused by copying wrong files...
