### ISSUE TITLE
Hardware requirements for training?

### ISSUE THREAD

**Issue by Becomebright** [yanbeic/CCL#4]
Thanks a lot for your insightful work. Since I want to reproduce your method, I wonder how many computation resources you used and how long you spent training your network? Looking forward to your reply.

**Comment by yanbeic** [comment]
We used GeForce RTX 2080 Ti x 2 on UCF101 (<1 days), GeForce RTX 2080 Ti x 4 on ActivityNet (<3 days).

**Comment by Becomebright** [comment]
What about VGGSound?

**Comment by yanbeic** [comment]
GeForce RTX 2080 Ti x 4 (around 1 week)

**Comment by Becomebright** [comment]
Got it. Thanks a lot.
